// Import the TranscriptionStatus type from our custom hook.
// Using "import type" means this import only exists at compile time
// and is removed from the final JavaScript bundle.
import type {
  TranscriptionLatency,
  TranscriptionStatus,
} from "@/hooks/useLiveTranscription";

// Defines the props (inputs) that this React component expects.
type LiveTranscriptProps = {
  // Current transcript generated by Whisper.  
  transcript: string;

  // Current state of the transcription pipeline
  // (idle, loading-model, transcribing, etc.).  
  status: TranscriptionStatus;

  // Model download progress (0-100).
  // Null means progress information is not available.  
  modelProgress: number | null;

  // Error message if transcription fails.  
  error: string | null;
  latency: TranscriptionLatency | null;
};

// React functional component that displays the live transcript UI.
export function LiveTranscript({
  transcript,
  status,
  modelProgress,
  error,
  latency,
}: LiveTranscriptProps) {
  return (
    // Main container with Tailwind CSS styling.    
    <section className="mt-8 rounded-xl border border-zinc-200 bg-zinc-50 p-5 dark:border-zinc-800 dark:bg-zinc-900/50">
      {/* Header containing the title and current transcription status */}      
      <div className="flex items-center justify-between gap-4">
        <h2 className="font-semibold text-zinc-950 dark:text-zinc-50">
          Live transcript
        </h2>
        {/* Human-readable status text (Loading model, Listening, etc.) */}        
        <span className="text-xs font-medium uppercase tracking-wide text-zinc-500">
          {formatTranscriptionStatus(status, modelProgress)}
        </span>
      </div>
      {/* Show an explanation while the Whisper model is downloading. */}
      {status === "loading-model" ? (
        <p className="mt-3 text-sm text-zinc-500">
          Whisper is loading before recording begins. The model is downloaded
          once and cached by your browser.
        </p>
      ) : null}
      {/* Display any transcription error to the user. */}
      {error ? <p className="mt-3 text-sm text-red-600">{error}</p> : null}

      {/* 
        Display the live transcript.
        aria-live="polite" tells screen readers to announce new transcript
        text when it changes without interrupting the user.
      */}
      <p
        className="mt-4 min-h-28 whitespace-pre-wrap text-base leading-7 text-zinc-800 dark:text-zinc-200"
        aria-live="polite"
      >
        {/* 
          If we have transcript text, display it.
          Otherwise, show a placeholder message until speech begins.
        */}        
        {transcript || "Your words will appear here a few seconds after you start speaking."}
      </p>
      {latency ? (
        <div className="mt-4 border-t border-zinc-200 pt-3 text-xs text-zinc-500 dark:border-zinc-800">
          <p className="font-medium text-zinc-700 dark:text-zinc-300">
            Latest sound-to-screen latency: {formatMilliseconds(latency.totalMs)}
          </p>
          <p className="mt-1">
            Queue + decode {formatMilliseconds(latency.queueAndDecodeMs)} · inference{" "}
            {formatMilliseconds(latency.inferenceMs)} · render {formatMilliseconds(latency.renderMs)}
          </p>
        </div>
      ) : null}
    </section>
  );
}

function formatMilliseconds(milliseconds: number): string {
  return `${Math.round(milliseconds).toLocaleString()} ms`;
}
/*
  Converts internal transcription states into user-friendly labels.
  Examples:
    loading-model + 35  -> "Loading model 35%"
    loading-model + null -> "Loading model"
    transcribing        -> "Listening"
    idle                -> "idle"
*/
function formatTranscriptionStatus(
  status: TranscriptionStatus,
  progress: number | null,
): string {
  // Show download progress while Whisper is loading.  
  if (status === "loading-model") {
    return progress === null ? "Loading model" : `Loading model ${progress}%`;
  }
  // "transcribing" is more technical, so display "Listening" instead.  
  if (status === "transcribing") {
    return "Listening";
  }
  // Return all other status values unchanged.  
  return status;
}
